---

- name: common roles
  hosts:
    - caladan
    - narwhal
    - fugu
    - snitch
  become: true
  roles:
    - basic
    - users
    - sshd
  vars:
    users:
      - rilla
      - ansible
      - gopass
      - woodpecker

- name: quality of life tools
  hosts:
    - caladan
    - narwhal
    - fugu
  become: true
  roles:
    - quality_of_life

- name: wifi setup
  hosts: snitch
  become: true
  roles:
    - wifi

- name: caladan-specific things
  hosts: caladan
  become: true
  roles:
    - tinyproxy

- name: wireguard
  hosts:
    - caladan
    - fugu
  become: true
  roles:
    - wireguard

- name: lbu commit
  hosts: snitch
  become: true
  roles:
    - lbu_commit

- name: setup gopass
  become: true
  hosts:
    - caladan
    - fugu
    - narwhal
  roles:
    - gopass
  tags: gopass
