- name: snitch deployment
  hosts: snitch
  become: yes
  become_method: doas
  roles:
    - basic
    - users
    - sshd
  vars:
    users:
      - rilla
      - ansible
  post_tasks:
    - name: lbu commit
      lbu:
        commit: true
