---
- name: snitch deployment
  hosts: snitch
  become: true
  roles:
    - basic
    - users
    - sshd
    - wifi
    - lbu_commit
  vars:
    users:
      - rilla
      - ansible

- name: caladan deployment
  hosts: caladan
  become: true
  roles:
    - basic
    - users
    - sshd
    - quality_of_life
    - tinyproxy
  vars:
    users:
      - rilla
      - ansible
      - woodpecker

- name: narwhal deployment
  hosts: narwhal
  become: true
  roles:
    - basic
    - users
    - sshd
    - quality_of_life
  vars:
    users:
      - rilla
      - ansible
      - woodpecker

- name: fugu deployment
  hosts: fugu
  become: true
  roles:
    - basic
    - users
    - sshd
    - quality_of_life
  vars:
    users:
      - rilla
      - ansible
