---
- name: snitch deployment
  hosts: snitch
  become: true
  roles:
    - basic
    - users
    - sshd
    - wifi
  vars:
    users:
      - rilla
      - ansible
    use_lbu: true
  post_tasks:
    - name: lbu commit
      lbu:
        commit: true

- name: caladan deployment
  hosts: caladan
  become: true
  roles:
    - basic
    - users
    - sshd
    - quality_of_life
    - tinyproxy
  vars:
    users:
      - rilla
      - ansible
      - woodpecker
    use_lbu: false

- name: narwhal deployment
  hosts: narwhal
  become: true
  roles:
    - basic
    - users
    - sshd
    - quality_of_life
  vars:
    users:
      - rilla
      - ansible
      - woodpecker

- name: fugu deployment
  hosts: fugu
  become: true
  roles:
    - basic
    - users
    - sshd
    - quality_of_life
  vars:
    users:
      - rilla
      - ansible
