---
all:
  hosts:

    snitch:
      ansible_host: snitch
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: doas
      use_lbu: true

    caladan:
      ansible_host: caladan
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: doas
      use_lbu: false

    narwhal:
      ansible_host: narwhal
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: sudo

    fugu:
      ansible_host: fugu
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/local/bin/python3
      ansible_become_method: doas
