---
all:
  hosts:

    pikvm:
      ansible_host: pikvm
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: doas
      dags:
        - acme_rsync

    snitch:
      ansible_host: snitch
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: doas
      use_lbu: true
      alpine_version: v3.16
      alpine_repos:
        - main

    suricata:
      ansible_host: suricata
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: doas
      use_lbu: true
      alpine_version: v3.16
      alpine_repos:
        - main
        - community
      mounts:
        - path: "/media/mmcblk0p1"
          src: "0EB4-4BBF"
          fstype: "vfat"
          opts: "noauto,defaults"
          passno: "0"
        - path: "/boot"
          src: "/media/mmcblk0p1/boot"
          fstype: "none"
          opts: "defaults,bind"
          passno: "0"
        - path: "/media/mmcblk0p2"
          src: "UUID=75d4943d-2a1a-4f76-9f60-cff99b4d2e1f"
          fstype: "ext4"
          opts: "defaults"
          passno: "0"
        - path: "/var/lib/builder/src"
          src: "/media/mmcblk0p2/src"
          fstype: "none"
          opts: "bind"
          passno: "0"
        - path: "/mnt/btr_pool"
          src: "/dev/mapper/disk0"
          fstype: "btrfs"
          opts: "subvolid=5,noatime"
          passno: "0"

      rpi_cfg:
        - "enable_uart=1"
        - "otg_mode=1"
      dmcrypt_targets:
        - name: "WDC WDS400T1R0A"
          target: "disk0"
          source_uuid: "202c924c-ee53-4321-9efd-1f776e939702"
          key: "/luks_key.asc:gpg"
          remdev: "/dev/mmcblk0p2"
        - name: "Samsung SSD 870"
          target: "disk1"
          source_uuid: "247ea237-54ce-45d2-9974-04344c06aba4"
          key: "/luks_key.asc:gpg"
          remdev: "/dev/mmcblk0p2"

    caladan:
      ansible_host: caladan
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: doas
      use_lbu: false
      alpine_version: v3.16
      alpine_repos:
        - main
        - community

    narwhal:
      ansible_host: narwhal
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: doas

    fugu:
      ansible_host: fugu
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/local/bin/python3
      ansible_become_method: doas
