all:
  hosts:

    snitch:
      ansible_host: snitch
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3

    caladan:
      ansible_host: caladan
      ansible_user: rilla
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
