---
all:
  hosts:

    snitch:
      ansible_host: snitch
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: doas
      use_lbu: true
      alpine_version: v3.16
      alpine_repos:
        - main

    suricata:
      ansible_host: suricata
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: doas
      use_lbu: true
      alpine_version: v3.16
      alpine_repos:
        - main
        - community
      mounts:
        - path: "/media/mmcblk0p1"
          src: "0EB4-4BBF"
          fstype: "vfat"
          opts: "noauto,defaults"
          passno: "0"
        - path: "/media/mmcblk0p2"
          src: "UUID=75d4943d-2a1a-4f76-9f60-cff99b4d2e1f"
          fstype: "ext4"
          opts: "noauto,defaults"
          passno: "0"
        - path: "/var/lib/builder/src"
          src: "/media/mmcblk0p2/src"
          fstype: "none"
          opts: "bind"
          passno: "0"

    caladan:
      ansible_host: caladan
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: doas
      use_lbu: false
      alpine_version: v3.16
      alpine_repos:
        - main
        - community

    narwhal:
      ansible_host: narwhal
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_method: sudo

    fugu:
      ansible_host: fugu
      ansible_user: ansible
      ansible_port: 22
      ansible_python_interpreter: /usr/local/bin/python3
      ansible_become_method: doas
