---

- name: add gopass apt key
  get_url:
    url: https://packages.gopass.pw/repos/gopass/gopass-archive-keyring.gpg
    dest: /etc/apt/trusted.gpg.d/gopass-archive-keyring.gpg

- name: add gopass repo
  apt_repository:
    repo: deb https://packages.gopass.pw/repos/gopass stable main
    filename: gopass.sources
    update_cache: true
    state: present

- name: install gopass
  apt:
    name:
      - gopass
    state: present
