---

- name: install gopass
  include_tasks: install.yml

- name: copy ssh keys
  include_tasks: ssh_keys.yml

- name: gitconfig
  include_tasks: gitconfig.yml

- name: import gpg keys
  include_tasks: gnupg.yml

- name: clone password store
  git:
    repo: git@git.narwhal.monotremata.xyz:lan/password-store.git
    dest: /var/lib/gopass/.password-store
  become_user: gopass
