---

- name: make gopass ssh directory
  file:
    state: directory
    path: /var/lib/gopass/.ssh
    owner: gopass
    group: gopass
    mode: '0700'

- name: copy gopass private ssh key
  copy:
    src: "host_files/gopass/ssh/{{ ansible_hostname }}/id_ed25519"
    dest: "/var/lib/gopass/.ssh/id_ed25519"
    owner: gopass
    group: gopass
    mode: '0600'

- name: copy gopass public ssh key
  copy:
    src: "host_files/gopass/ssh/{{ ansible_hostname }}/id_ed25519.pub"
    dest: "/var/lib/gopass/.ssh/id_ed25519.pub"
    owner: gopass
    group: gopass
    mode: '0644'
