---

- name: uncompress bcm2835-1.68
  unarchive:
    src: /var/lib/builder/src/pibox-os/pwm-fan/bcm2835-1.68.tar.gz
    dest: /var/lib/builder/src/pibox-os/pwm-fan
    remote_src: true
    creates: /var/lib/builder/src/pibox-os/pwm-fan/bcm2835-1.68/configure
  become_user: builder

- name: ./configure bcm2835-1.68
  shell:
    chdir: /var/lib/builder/src/pibox-os/pwm-fan/bcm2835-1.68
    cmd: ./configure
    creates: /var/lib/builder/src/pibox-os/pwm-fan/bcm2835-1.68/Makefile
  become_user: builder

- name: build bcm2835-1.68
  make:
    chdir: /var/lib/builder/src/pibox-os/pwm-fan/bcm2835-1.68
    target: all
  become_user: builder

- name: install bcm2835-1.68
  make:
    chdir: /var/lib/builder/src/pibox-os/pwm-fan/bcm2835-1.68
    target: install
