---
- name: install python3
  apk:
    name: python3
  when: ansible_distribution == "Alpine"

- name: install python3
  apt:
    name: python3
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: install python3
  openbsd_pkg:
    name: python3
  when: ansible_distribution == "OpenBSD"
