---
- name: install python3
  apk:
    name:
      - acl
      - python3
  when: ansible_distribution == "Alpine"

- name: install python3
  apt:
    name:
      - acl
      - python3
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: install python3
  openbsd_pkg:
    name:
      - python3
  when: ansible_distribution == "OpenBSD"

- name: install python3
  pacman:
    name:
      - python3
  when: ansible_distribution == "Archlinux"
