- name: install python3
  apk:
    name: python3

- name: create group 'rilla'
  group:
    name: rilla
    gid: 1000

- name: create user 'rilla'
  user:
    name: rilla
    uid: 1000
    group: rilla
    home: /home/rilla
    groups:
      - rilla
      - wheel
