---
- name: create group 'deploy'
  group:
    name: deploy
    gid: 700

- name: create group 'media'
  group:
    name: media
    gid: 701

- name: determine available groups
  getent:
    database: group

- name: create users
  include_tasks: "{{ username }}.yml"
  loop: "{{ users }}"
  loop_control:
    loop_var: username
