---

- name: install client for Debian / Ubuntu
  apt:
    name: nut-client
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: set up /etc/nut/upsmon.conf
  blockinfile:
    path: /etc/nut/upsmon.conf
    block: |
      MONITOR {{ nut_device.name }}@{{ nut_host }} 1 upsmon {{ nut_upsmon_password }} {{ nut_types[nut_mode] }}

- name: start and enable nut-upsmon
  service:
    name: nut-upsmon
    runlevel: default
    state: started
    enabled: true
  when: ansible_distribution == "Alpine"

- name: start and enable nut-monitor
  systemd:
    name: nut-monitor
    state: started
    enabled: true
  when: ansible_distribution in ["Debian", "Ubuntu"]
