- name: commit rilla's authorized ssh keys
  lbu:
    include:
      - /home/rilla/.ssh/authorized_keys
  when: rilla_keys.changed

- name: commit ansible's authorized ssh keys
  lbu:
    include:
      - /var/lib/ansible/.ssh/authorized_keys
  when: ansible_keys.changed

- name: install openssh
  apk:
    name: openssh

- name: enable sshd service
  service:
    name: sshd
    enabled: yes
    state: started
