- name: ssh_host_ed25519_key-cert.pub
  copy:
    src: "host_files/{{ ansible_hostname }}/ssh_host_ed25519_key-cert.pub"
    dest: "/etc/ssh/ssh_host_ed25519_key-cert.pub"
    mode: '0644'
    owner: root
    group: root

- name: ssh_host_ed25519_key.pub
  copy:
    src: "host_files/{{ ansible_hostname }}/ssh_host_ed25519_key.pub"
    dest: "/etc/ssh/ssh_host_ed25519_key.pub"
    mode: '0644'
    owner: root
    group: root

- name: ssh_host_ed25519_key
  copy:
    src: "host_files/{{ ansible_hostname }}/ssh_host_ed25519_key"
    dest: "/etc/ssh/ssh_host_ed25519_key"
    mode: '0600'
    owner: root
    group: root

- name: copy user_ca.pub
  copy:
    src: user_ca.pub
    dest: "/etc/ssh/user_ca.pub"
    mode: '0644'
    owner: root
    group: root

- name: copy ssh_known_hosts
  copy:
    src: ssh_known_hosts
    dest: "/etc/ssh/ssh_known_hosts"
    mode: '0644'
    owner: root
    group: root
