---
- name: set sshd config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0644'
    owner: root

- name: create authorized_keys directory
  file:
    state: directory
    path: /etc/ssh/authorized_keys

- name: setup host ssh certificates
  include_tasks: certs.yml

- name: setup alpine ssh
  include_tasks: alpine.yml
  when: ansible_distribution == "Alpine"

- name: setup arch ssh
  include_tasks: archlinux.yml
  when: ansible_distribution == "Archlinux"
